bangkok_bbox:
  lat_min: 13.4
  lat_max: 14.0
  lon_min: 100.3
  lon_max: 100.9

accidents:
  raw_dir: "data/raw/MOT_accident_data"
  clean_gpkg: "data/processed/accident_bangkok/accidents_clean.gpkg"
  clean_parquet: "data/processed/accident_bangkok/accidents_clean.parquet"
  projected_crs: "EPSG:32647"
  valid_weather:
    - "แจ่มใส"
    - "ฝนตก"
    - "มีหมอก/ควัน/ฝุ่น"
    - "มืดครึ้ม"
    - "อื่นๆ"
    - "ภัยธรรมชาติ เช่น พายุ น้ำท่วม"

road_segments:
  input: "data/raw/osm/osm_roads.gpkg"
  output: "data/processed/road_segments.gpkg"
  intersections_output: "data/processed/intersections.gpkg"
  snapped_accidents_output: "data/processed/accidents_snapped.gpkg"
  snap_max_distance_m: 50
  segment_length_m: 100
  projected_crs: "EPSG:32647"
  drivable_highway_types:
    - motorway
    - motorway_link
    - trunk
    - trunk_link
    - primary
    - primary_link
    - secondary
    - secondary_link
    - tertiary
    - tertiary_link
    - unclassified
    - residential

boundary:
  bangkok: "data/raw/bangkok_boundary.gpkg"

osm:
  place: "Bangkok, Thailand"
  layers:
    - name: roads
      output_path: "data/raw/osm/osm_roads.gpkg"
      tags:
        highway: true

    - name: buildings
      output_path: "data/raw/osm/osm_buildings.gpkg"
      tags:
        building: true

    - name: landuse
      output_path: "data/raw/osm/osm_landuse.gpkg"
      tags:
        landuse: true

    - name: poi
      output_path: "data/raw/osm/osm_poi.gpkg"
      tags:
        amenity: [school, university, hospital, bar, restaurant, fuel, nightclub]
        shop: [mall, supermarket, convenience]


datasets:
  - year: 2019
    resource_id: 4d919e5b-aa06-4fe4-8a13-5571747a1254

  - year: 2020
    resource_id: 40476c7b-4194-4dc2-aba5-7326819ed071

  - year: 2021
    resource_id: d0a8601a-3ee5-4ce8-8e9d-3dae3915dc30

  - year: 2022
    resource_id: 733b7874-bd5f-44b9-b271-650890b061f2

  - year: 2023
    resource_id: 661f2ead-1f28-4cd9-8a67-1bef76b33ef6

  - year: 2024
    resource_id: 83e9fae0-5f33-45e7-9a6d-6d5ad2060a08

  - year: 2025
    resource_id: e1db5e93-2b70-4ee4-b6d7-7ead76d14a09
